### ISSUE TITLE
[C5][Publisher] Add UI/REST API validations

### ISSUE THREAD

**Issue by tmkasun** [wso2/carbon-apimgt#4281]
Getting following error when updating policies due to invalid endpoint URL provided during API creation.
Need to add input validations in both UI level and REST API.
```Java
[2017-07-10 20:35:04,979]  WARN {org.wso2.msf4j.internal.MSF4JMessageProcessor} - Unmapped exception java.lang.NullPointerException
	at org.wso2.carbon.apimgt.core.impl.APIPublisherImpl.validateEndpoints(APIPublisherImpl.java:361)
	at org.wso2.carbon.apimgt.core.impl.APIPublisherImpl.updateAPI(APIPublisherImpl.java:453)
	at org.wso2.carbon.apimgt.rest.api.publisher.impl.ApisApiServiceImpl.apisApiIdPut(ApisApiServiceImpl.java:955)
	at org.wso2.carbon.apimgt.rest.api.publisher.ApisApi.apisApiIdPut(ApisApi.java:375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:139)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$0(MSF4JMessageProcessor.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by rswijesena** [comment]
we should receive a proper error message from the MS4J side in this kind of cases.
