### ISSUE TITLE
When application group sharing is enabled, ApiMgtDAO thrown NPE for getApplicationByClientId

### ISSUE THREAD

**Issue by gusto2** [wso2/carbon-apimgt#5874]
**Description:**

When application group sharing is enabled

```
 <APIStore> 
    <GroupingExtractor>org.wso2.carbon.apimgt.impl.DefaultGroupIDExtractorImpl</GroupingExtractor>
```

it is not possible to generate a token from the store with following exception

```
TID: [-1234] [] [2018-11-27 12:56:11,039] ERROR {org.wso2.carbon.identity.oauth2.OAuth2Service} -  Error occurred while issuing the access token for Client ID : 4t4aXBQTmW55av0KgGVuIseqGvAa, User ID null, Scope : [default] and Grant Type : client_credentials {org.wso2.carbon.identity.oauth2.OAuth2Service}
java.lang.NullPointerException
	at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getApplicationByClientId(ApiMgtDAO.java:11516)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.getApplicationByClientId(APIUtil.java:7426)
	at org.wso2.carbon.apimgt.keymgt.issuers.APIMTokenIssuer.renewAccessTokenPerRequest(APIMTokenIssuer.java:157)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.accessTokenNotRenewedPerRequest(AbstractAuthorizationGrantHandler.java:808)
	at org.wso2.carbon.identity.oauth2.token.handlers.grant.AbstractAuthorizationGrantHandler.issue(AbstractAuthorizationGrantHandler.java:129)
```

backtraced the code to 

```
                if (multiGroupAppSharingEnabled) {
                    if (application.getGroupId().isEmpty()) {
                        application.setGroupId(getGroupId(application.getId()));
                    }
                }
```

and the direct cause of the issue is that `application.getGroupId()` is null.

**Suggested Assignees:**

**Affected Product Version:**
WSO2AM-2.6.0

**OS, DB, other environments details and versions:**    
Tested on Win10, wso2am-2.6.0, Oracle XE or H2

**Steps to reproduce:**

 - Enable GroupingExtractor in api-manager.xml
 - In the API Store create an application
 - generate keys

**Related Issues:**

**Comment by mushthaq33** [comment]
Fixed with wso2/carbon-apimgt#5841
