### ISSUE TITLE
Removing default version when default environment is not configured throws an NPE

### ISSUE THREAD

**Issue by jhatzenb** [wso2/carbon-apimgt#8572]
### Description:
When creating an API with 'I Have an Existing API' the api.yaml is created with 'Production and Sandbox' in environments.
If this name is not configured in deployment.toml the class [APIGatewayManager](https://github.com/wso2/carbon-apimgt/blob/v6.6.163/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java) in function removeDefaultAPIFromGateway throws an NPE:
`An unknown exception has been captured by the global exception mapper. java.lang.NullPointerException
at org.wso2.carbon.apimgt.impl.utils.APIGatewayAdminClient.<init>(APIGatewayAdminClient.java:50)
at org.wso2.carbon.apimgt.impl.APIGatewayManager.removeDefaultAPIFromGateway_aroundBody30(APIGatewayManager.java:798)
at org.wso2.carbon.apimgt.impl.APIGatewayManager.removeDefaultAPIFromGateway(APIGatewayManager.java:790)`
when trying removing default version (Make this the default version: Yes to No)

### Steps to reproduce:
- Configure an environment name other than 'Production and Sandbox' in deployment.toml
- Start WSO2 API Management
- Log to WSO2 API Publisher 3.1.0
- Create an API with a Swagger file ('I Have an Existing API')
- Go to Design Configurations and select Make this the default version: Yes
- Save
-  Go to Design Configurations and select Make this the default version: No

### Affected Product Version:
wso2am-3.1.0

### Environment details (with versions):
- OS: RedHat
- Client: 
- Env (Docker/K8s):

**Comment by jhatzenb** [comment]
This issue can be corrected to apply the same NPE prevention like in other methods `if (environment == null) {continue;}` on line 797 [APIGatewayManager](https://github.com/wso2/carbon-apimgt/blob/v6.6.163/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIGatewayManager.java#L797)
