### ISSUE TITLE
Error processing GET request for : URL exception during a Load test 

### ISSUE THREAD

**Issue by shiranmohomad** [wso2/carbon-apimgt#9317]
### Description:

We were able to see that API invocations starts to fail with a null pointer exception in one of the customer's environment. This starts to happen during a Performance Test with a higher concurrency and it keep reproducing until the server is restarted or republishing the API.Please find the below stack trace.

`ERROR {org.apache.synapse.transport.passthru.ServerWorker} - Error processing GET request for : /dxl/customerManagement/v2/userProfile/9860303033?parentMSISDN=9860303033. java.lang.NullPointerException
at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody42(APIAuthenticationHandler.java:419)
at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:413)
at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody36(APIAuthenticationHandler.java:349)
at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:320)
at org.apache.synapse.rest.API.process(API.java:368)
at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149)
at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:327)
at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:98)
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:384)
at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:190)
at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)`

This issue was reproduced after the following changes that have been done in the attached diff file.

[diff.zip](https://github.com/wso2/carbon-apimgt/files/5377591/diff.zip)

### Affected Product Version:
Version: 3.1.0

**Comment by HiranyaKavishani** [comment]
Close the issue as per the commit
